title: naegi.github.io
paginate: 5
theme: PaperMod

output: 
  home: 
    - html 
    - json
minify:
  disableXML: true
  minifyOutput: true

params:
  DateFormat: "January 2, 2006"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  math: true

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: false

  label:
    text: "Home"

  editPost:
    URL: "https://github.com/naegi/naegi.github.io"
    Text: "Report an issue" # edit text
    appendFilePath: false

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: archive
      name: archive
      url: /archive/
      weight: 20
markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
